version: '3'
services:
  database:
    image: mariadb
    networks:
      - runner
    environment:
      - "MARIADB_ROOT_PASSWORD=123"
      - "MARIADB_DATABASE=runner"
      - "MARIADB_USER=runner"
      - "MARIADB_PASSWORD=runner"
    volumes:
      - "./target/mariadb:/var/lib/mysql"

  runner:
    container_name: exactauth
    restart: unless-stopped
    build:
      context: ./
      ssh:
        - "default"

    networks:
      - runner
    depends_on:
      - database
    environment:
      - "MYSQL_HOST=database"
      - "MYSQL_USER=runner"
      - "MYSQL_PASSWORD=runner"
      - "MYSQL_DB=runner"
      - "EXACT_CLIENT_ID=bac401ab-7d4e-4cb6-92dd-8df388553c5b"
      - "EXACT_CLIENT_SECRET=cCAPV7VhtNiF"
      - "REDIRECT_URI=https://mrf.local:8443/api/v1/logged-in"
      - "MRAUTH_URL=http://localhost:3444"
    ports:
      - "8081:8080"

networks:
  runner:
    external: false